backend:
  name: git-gateway
  branch: master # or the branch you're using

media_folder: "static/images" # Path where uploaded images will be stored
public_folder: "/images"      # Public path for the images

collections:
  - name: "headings"
    label: "Headings"
    folder: "content/headings"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Heading Content", name: "content", widget: "text"}
      
  - name: "paragraphs"
    label: "Paragraphs"
    folder: "content/paragraphs"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Paragraph Text", name: "text", widget: "markdown"}
  
  - name: "images"
    label: "Images"
    folder: "content/images"
    create: true
    fields:
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Alt Text", name: "alt", widget: "string"}

  - name: "multi-images"
    label: "Multi Images"
    folder: "content/multi-images"
    create: true
    fields:
      - {label: "Gallery", name: "gallery", widget: "list", field: {label: "Image", name: "image", widget: "image"}}
