backend:
  name: git-gateway
  branch: master # or the branch you're using

media_folder: "static/images" # Path where uploaded images will be stored
public_folder: "/images"      # Public path for the images

collections:
  - name: "destinations"
    label: "Destinations"
    folder: "content/destinations"
    create: true
    fields:
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Multi Image", name: "multi_image", widget: "list", field: {label: "Image", name: "image", widget: "image"}}
      - {label: "Overview Text", name: "overview_text", widget: "markdown"}

  - name: "wellbeing_hotels"
    label: "Wellbeing Hotels"
    folder: "content/wellbeing-hotels"
    create: true
    fields:
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Multi Image", name: "multi_image", widget: "list", field: {label: "Image", name: "image", widget: "image"}}
      - {label: "Overview Text", name: "overview_text", widget: "markdown"}

  - name: "retreats"
    label: "Retreats"
    folder: "content/retreats"
    create: true
    fields:
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Multi Image", name: "multi_image", widget: "list", field: {label: "Image", name: "image", widget: "image"}}
      - {label: "Overview Text", name: "overview_text", widget: "markdown"}

  - name: "online_classes"
    label: "Online Classes"
    folder: "content/online-classes"
    create: true
    fields:
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Multi Image", name: "multi_image", widget: "list", field: {label: "Image", name: "image", widget: "image"}}
      - {label: "Overview Text", name: "overview_text", widget: "markdown"}

  - name: "wellbeing_inspirations"
    label: "Wellbeing Inspirations"
    folder: "content/wellbeing-inspirations"
    create: true
    fields:
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Multi Image", name: "multi_image", widget: "list", field: {label: "Image", name: "image", widget: "image"}}
      - {label: "Overview Text", name: "overview_text", widget: "markdown"}
